name: Build and Release with Nuitka

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka
          pip install PyQt5 QFluentWidgets
          pip install -r requirements.txt || true

      - name: Build with Nuitka
        run: |
          mkdir dist
          python -m nuitka xianmetro/main.py --standalone --enable-plugin=qt --output-dir=dist --include-package=xianmetro --include-data-dir=xianmetro/assets=xianmetro/assets --nofollow-import-to=tests

      - name: Package artifact
        run: |
          powershell Compress-Archive -Path dist\* -DestinationPath xianmetro.zip

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: xianmetro.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
